### ISSUE TITLE
new tab

### ISSUE THREAD

**Issue by solara322** [Drarox/GoogleYoutubeRedirect#1]
Hi.

It doesn't work if I open the preview in a new tab (using midclick). 
I only use this method.
Is there any solution for this?

**Comment by tamtamree** [comment]
same here
firefox and chrome

**Comment by Drarox** [comment]
Hi,

Thank you for reporting this issue.

Unfortunately, Google has changed the href value of the HTML <a> element for the thumbnail to "#". Consequently, when the link is opened in a new tab, it simply appends "#" to the current URL, resulting in the same search results page being opened. As a result, the extension is unable to determine which video to open. Google's behavior in this regard is quite frustrating.
