### ISSUE TITLE
The “YouTube” Tab Doesn’t Appear on Google Search Any More

### ISSUE THREAD

**Issue by easonwong-de** [Drarox/GoogleYoutubeRedirect#2]
Hi, @Drarox. I’ve been using your amazing extension for a while. But the “YouTube” tab seems to cease to appear on Google search.

See screenshot:

![Screenshot 2024-12-17 at 01-28-46 something - Google Search](https://github.com/user-attachments/assets/ca52a407-3cf8-4c55-b794-d6da7075c454)

**Comment by Drarox** [comment]
Hi, Thanks for the feedback! Google keeps changing its interface every few months, which is very annoying... Anyway, I’ve updated the extension to work with the new interface. The fix is available in version 1.2, which is already published on Firefox and currently under review on Chrome.

**Comment by easonwong-de** [comment]
Thanks for the quick fix! It’s working perfectly now!
